"""TracedGenner — framework wrapper that captures every inference call.

The inference boundary is the single chokepoint for training-data capture.
All LLM traffic generated by the harness goes through ``TracedGenner``,
which:

1. Requires a ``phase`` tag on every call (so downstream training-data
   filtering can partition by harness-defined phase taxonomy).
2. Honors ``cancel_event`` set by the framework on wall-clock timeout or
   external stop signal — returns ``Err("cancelled: ...")`` without
   issuing the call.
3. Records a :class:`TrajectoryRecord` on the attached
   :class:`EventRecorder` after every call (success or failure).

Subclassable — users override ``plist_completion`` (calling ``super``) to
add before/after behavior (redaction, synthetic errors, per-call budget
checks) without the ABC growing hooks.
"""

from __future__ import annotations

import threading
from datetime import datetime
from typing import TYPE_CHECKING, Any, Callable

from result import Err, Ok, Result

from src.genner.Base import Genner
from src.harness.recorder import EventRecorder, TrajectoryRecord
from src.observability.types import InferenceResult, UsageInfo
from src.typing.message import Message

if TYPE_CHECKING:
    from src.harness.budget import BudgetLedger


_CANCELLED_PREFIX = "cancelled:"


class TracedGenner:
    """Framework wrapper around a concrete ``Genner`` chain.

    The harness sees ``TracedGenner`` — *never* a raw ``Genner``. The
    ``phase`` kwarg is required on every call and serves as the training-
    data partition key. The framework does not interpret ``phase``; it
    simply records what the harness supplied.

    This class deliberately does NOT subclass :class:`Genner`. The signature
    differs (required ``phase`` kwarg) and only harnesses ever call it.
    """

    def __init__(
        self,
        inner: Genner,
        recorder: EventRecorder,
        cancel_event: threading.Event,
        *,
        episode_id: str,
        on_inference: Callable[[UsageInfo | None], None] | None = None,
        budget_ledger: "BudgetLedger | None" = None,
    ) -> None:
        self._inner = inner
        self._recorder = recorder
        self._cancel_event = cancel_event
        self._episode_id = episode_id
        # Optional framework hook fired after every completion (success or
        # failure). Used by the framework to push live prompt-token +
        # harness-telemetry updates to the progress display.
        self._on_inference = on_inference
        self._budget_ledger = budget_ledger

    @property
    def inner(self) -> Genner:
        """Access the wrapped Genner. Use sparingly — bypassing TracedGenner
        means the call is NOT captured in training data."""
        return self._inner

    @property
    def recorder(self) -> EventRecorder:
        return self._recorder

    def set_budget_ledger(self, budget_ledger: "BudgetLedger | None") -> None:
        self._budget_ledger = budget_ledger

    def plist_completion(
        self,
        messages: list[Message],
        *,
        phase: str,
        tools: list[dict[str, Any]] | None = None,
        tool_choice: Any = None,
        meta: dict[str, Any] | None = None,
    ) -> Result[InferenceResult, str]:
        """Run one completion, recording the trajectory.

        Checks ``cancel_event`` before the call so runaway harnesses unwind
        at the next tick. The ``phase`` tag partitions training data; the
        harness chooses its own taxonomy.
        """
        if self._cancel_event.is_set():
            error = f"{_CANCELLED_PREFIX} cancel_event set before plist_completion"
            self._record(
                phase=phase,
                messages=messages,
                response="",
                usage=None,
                success=False,
                error_message=error,
                meta=meta,
            )
            self._fire_observer(None)
            return Err(error)

        # Attach phase + episode_id to the first message's `meta` so the
        # downstream MetricsGenner (genner_wrapper.py) can attribute the
        # InferenceMetric correctly. Without this, _resolve_phase_name
        # falls back to "unknown" and _resolve_episode_id to None, and
        # episode-scoped aggregation in generate_training_data.py returns
        # zero counters even though the calls are recorded.
        # Non-mutating: we copy the first message and overlay meta.
        inner_messages = self._inject_attribution_meta(messages, phase=phase, meta=meta)
        if tools is None and tool_choice is None:
            result = self._inner.plist_completion(inner_messages)
        else:
            result = self._inner.plist_completion(
                inner_messages,
                tools=tools,
                tool_choice=tool_choice,
            )
        match result:
            case Ok(inference_result):
                self._record(
                    phase=phase,
                    messages=messages,
                    response=inference_result.content,
                    usage=inference_result.usage,
                    success=True,
                    error_message=None,
                    meta=meta,
                )
                self._record_successful_llm_turn()
                self._fire_observer(inference_result.usage)
                return Ok(inference_result)
            case Err(error_message):
                self._record(
                    phase=phase,
                    messages=messages,
                    response="",
                    usage=None,
                    success=False,
                    error_message=error_message,
                    meta=meta,
                )
                self._fire_observer(None)
                return Err(error_message)

    # --- Internals ---

    def _record_successful_llm_turn(self) -> None:
        if self._budget_ledger is not None:
            self._budget_ledger.record_llm_turn()
        try:
            self._recorder.bump_counter("llm_turns")
        except Exception:
            pass

    def _inject_attribution_meta(
        self,
        messages: list[Message],
        *,
        phase: str,
        meta: dict[str, Any] | None,
    ) -> list[Message]:
        if not messages:
            return list(messages)
        attribution: dict[str, Any] = {
            "phase": phase,
            "episode_id": self._episode_id,
        }
        if meta:
            for k, v in meta.items():
                attribution.setdefault(k, v)
        first: dict[str, Any] = dict(messages[0])
        prior_meta = first.get("meta")
        merged_meta: dict[str, Any] = (
            dict(prior_meta) if isinstance(prior_meta, dict) else {}
        )
        for k, v in attribution.items():
            merged_meta.setdefault(k, v)
        first["meta"] = merged_meta
        out: list[Message] = list(messages)
        out[0] = first  # type: ignore[assignment]
        return out

    def _fire_observer(self, usage: UsageInfo | None) -> None:
        if self._on_inference is None:
            return
        try:
            self._on_inference(usage)
        except Exception:
            # Observer hooks are advisory and MUST NOT derail the episode —
            # they are wired up for UI progress, which is best-effort.
            pass

    def _record_meta(
        self,
        messages: list[Message],
        *,
        phase: str,
        meta: dict[str, Any] | None,
    ) -> dict[str, Any]:
        merged: dict[str, Any] = {}
        if messages:
            first_meta = messages[0].get("meta")
            if isinstance(first_meta, dict):
                merged.update(first_meta)
        if meta:
            merged.update(meta)
        merged.setdefault("phase", phase)
        merged.setdefault("episode_id", self._episode_id)
        return merged

    def _record(
        self,
        *,
        phase: str,
        messages: list[Message],
        response: str,
        usage: Any,
        success: bool,
        error_message: str | None,
        meta: dict[str, Any] | None,
    ) -> None:
        record = TrajectoryRecord(
            episode_id=self._episode_id,
            phase=phase,
            messages=list(messages),
            response=response,
            usage=usage,
            timestamp=datetime.now().isoformat(),
            success=success,
            error_message=error_message,
            meta=self._record_meta(messages, phase=phase, meta=meta),
        )
        self._recorder.record_inference(record)
